--- # RUNONCE PLAYBOOK EXAMPLE
- hosts: 34.244.223.174
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks: 
  - name: Run the uptime command on all hosts and log it
    raw: /usr/bin/uptime >> /root/uptime.log
  - name: List the var directory and log it
    raw: ls -al /var >> /root/dir.list
    run_once: true (It will run once just on the first host from the group) 
