
--- #The script module
- hosts: apacheweb
  user: ansible
  connection: ssh 
  sudo: yes 
  gather_facts: no
  tasks: 
  - script: /home/ansible/ansible/playbooks/system_uptime.sh > uptime.log creates=/home/ansible/uptime.log
    
